<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SubJenisCiptaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() 
    {
        DB::insert("INSERT INTO sub_jenis_ciptaans (id,jenis_ciptaan_id,nama_sub_jenis_ciptaan) VALUES
        (1, 1, 'Atlas'),
        (2, 1, 'Biografi'),
        (3, 1, 'Booklet'),
        (4, 1, 'Buku'),
        (5, 1, 'Buku Mewarnai'),
        (6, 1, 'Buku Panduan/Petunjuk'),
        (7, 1, 'Buku Pelajaran'),
        (8, 1, 'Buku Saku'),
        (9, 1, 'Bunga Rampai'),
        (10, 1, 'Cerita Bergambar'),
        (11, 1, 'Diktat'),
        (12, 1, 'Dongeng'),
        (13, 1, 'e-Book'),
        (14, 1, 'Ensiklopedia'),
        (15, 1, 'Jurnal'),
        (16, 1, 'Kamus'),
        (17, 1, 'Karya Ilmiah'),
        (18, 1, 'Karya Tulis'),
        (19, 1, 'Karya Tulis (Artikel)'),
        (20, 1, 'Karya Tulis (Disertasi)'),
        (21, 1, 'Karya Tulis (Skripsi)'),
        (22, 1, 'Karya Tulis (Tesis)'),
        (23, 1, 'Karya Tulis Lainnya'),
        (24, 1, 'Komik'),
        (25, 1, 'Laporan Penelitian'),
        (26, 1, 'Majalah'),
        (27, 1, 'Makalah'),
        (28, 1, 'Modul'),
        (29, 1, 'Naskah Drama / Pertunjukan'),
        (30, 1, 'Naskah Film'),
        (31, 1, 'Naskah Karya Siaran'),
        (32, 1, 'Naskah Karya Sinematografi'),
        (33, 1, 'Novel'),
        (34, 1, 'Perwajahan Karya Tulis'),
        (35, 1, 'Proposal Penelitian'),
        (36, 1, 'Puisi'),
        (37, 1, 'Resensi'),
        (38, 1, 'Resume/Ringkasan'),
        (39, 1, 'Saduran'),
        (40, 1, 'Sinopsis'),
        (41, 1, 'Tafsir'),
        (42, 1, 'Terjemahan'),
        (43, 2, 'Alat Peraga'),
        (44, 2, 'Arsitektur'),
        (45, 2, 'Baliho'),
        (46, 2, 'Banner'),
        (47, 2, 'Brosur'),
        (48, 2, 'Diorama'),
        (49, 2, 'Flyer'),
        (50, 2, 'Kaligrafi'),
        (51, 2, 'Karya Seni Batik'),
        (52, 2, 'Karya Seni Rupa'),
        (53, 2, 'Kolase'),
        (54, 2, 'Leaflet'),
        (55, 2, 'Motif Sasirangan'),
        (56, 2, 'Motif Tapis'),
        (57, 2, 'Motif Tenun Ikat'),
        (58, 2, 'Motif Ulos'),
        (59, 2, 'Pamflet'),
        (60, 2, 'Peta'),
        (61, 2, 'Poster'),
        (62, 2, 'Seni Gambar'),
        (63, 2, 'Seni Ilustrasi'),
        (64, 2, 'Seni Motif'),
        (65, 2, 'Seni Motif Lainnya'),
        (66, 2, 'Seni Pahat'),
        (67, 2, 'Seni Patung'),
        (68, 2, 'Seni Rupa'),
        (69, 2, 'Seni Songket'),
        (70, 2, 'Seni Terapan'),
        (71, 2, 'Seni Umum'),
        (72, 2, 'Sketsa'),
        (73, 2, 'Spanduk'),
        (74, 2, 'Ukiran'),
        (75, 3, 'Aransemen'),
        (76, 3, 'Lagu (Musik Dengan Tesk)'),
        (77, 3, 'Musik'),
        (78, 3, 'Musik Blues'),
        (79, 3, 'Musik Country'),
        (80, 3, 'Musik Dangdut'),
        (81, 3, 'Musik Elektronik'),
        (82, 3, 'Musik Funk'),
        (83, 3, 'Musik Gospel'),
        (84, 3, 'Musik Hip hop, Rap, Rapcore'),
        (85, 3, 'Musik Jazz'),
        (86, 3, 'Musik Karawitan'),
        (87, 3, 'Musik Klasik'),
        (88, 3, 'Musik Latin'),
        (89, 3, 'Musik Metal'),
        (90, 3, 'Musik Pop'),
        (91, 3, 'Musik Rhythm and Blues'),
        (92, 3, 'Musik Rock'),
        (93, 3, 'Musik Ska, Reggae, Dub'),
        (94, 3, 'Musik Tanpa Teks'),
        (95, 4, 'Film'),
        (96, 4, 'Film Cerita'),
        (97, 4, 'Film Dokumenter'),
        (98, 4, 'Film Iklan'),
        (99, 4, 'Film Kartun'),
        (100, 4, 'Karya Rekaman Video'),
        (101, 4, 'Karya Siaran'),
        (102, 4, 'Karya Siaran Media Radio'),
        (103, 4, 'Karya Siaran Media Televisi dan Film'),
        (104, 4, 'Karya Siaran Video'),
        (105, 4, 'Karya Sinematografi'),
        (106, 4, 'Kuliah'),
        (107, 4, 'Reportase'),
        (108, 5, 'Karya Fotografi'),
        (109, 5, 'Potret'),
        (110, 6, 'Drama / Pertunjukan'),
        (111, 6, 'Drama Musikal'),
        (112, 6, 'Ketoprak'),
        (113, 6, 'Komedi/Lawak'),
        (114, 6, 'Koreografi'),
        (115, 6, 'Lenong'),
        (116, 6, 'Ludruk'),
        (117, 6, 'Opera'),
        (118, 6, 'Pantomim'),
        (119, 6, 'Pentas Musik'),
        (120, 6, 'Pewayangan'),
        (121, 6, 'Seni Akrobat'),
        (122, 6, 'Seni Pertunjukan'),
        (123, 6, 'Sirkus'),
        (124, 6, 'Sulap'),
        (125, 6, 'Tari (Sendra Tari)'),
        (126, 7, 'Ceramah'),
        (127, 7, 'Karya Rekaman Suara atau Bunyi'),
        (128, 7, 'Khutbah'),
        (129, 7, 'Pidato'),
        (130, 8, 'Basis Data'), 
        (131, 8, 'Kompilasi Ciptaan / Data'),
        (132, 8, 'Permainan Video'),
        (133, 8, 'Program Komputer')");
    }
}
